# Copyright 2025-2026 SGLang Team
# Licensed under the Apache License, Version 2.0 (the "License");
"""RWKV-7 chain speculative decoding on sglang spec-V2 (ADR-0006, Strategy B).

A small RWKV-7 *draft* proposes tokens by running greedy decode steps on its
own recurrent state; the *target* verifies them in ONE ``TARGET_VERIFY``
forward, reusing upstream's generic spec-v2 verify+commit machinery (the same
``NgramVerifyInput`` / ``eagle_sample`` / ``commit_mamba_states_after_verify``
path ``NGRAMWorker`` uses) instead of a bespoke hand-rolled verify. The only
genuinely new logic this worker owns is the *draft's own* recurrent-state
rollback (upstream's commit machinery only knows about the target).

Why not subclass ``EAGLEWorkerV2`` / ``StandaloneWorkerV2``: their draft path is
transformer-shaped (draft attention backend, draft cuda-graphs, tree mask) — a
recurrent RWKV draft has no attention or KV, so it cannot ride that machinery.
Instead we mirror ``NGRAMWorker`` (subclass ``BaseSpecWorker`` directly, build a
verify input from a non-EAGLE draft source, reuse the target verify), with the
draft source being a real 0.1B RWKV model instead of an n-gram corpus.

Chain shape (topk=1, verified against ``verify_tree_greedy_kernel_triton``,
NOT guessed): the verify window is ``K = speculative_num_draft_tokens``
positions, but position 0 is *not* a new guess — the greedy-tree-walk kernel
unconditionally accepts node 0 as the walk's root (mirrors EAGLE's "the first
token generated by the target model... is always accepted from the previous
iteration"). So position 0 must be ``t_last`` (the last already-committed
token, re-fed so the target emits a prediction for what follows it), and the
draft only needs to produce ``K-1`` genuine new guesses at positions 1..K-1:
    candidates = [t_last, d_0, d_1, ..., d_{K-2}]
target_predict[j] validates candidates[j+1]; target_predict[K-1] (after the
last real draft) is never checked against anything and becomes the bonus
token if the whole chain accepts. ``eagle_sample`` returns
``accept_lens = num_correct_drafts + 1`` (the "+1" is that free position-0
accept, NOT a bonus beyond the drafts — the real per-request draft accept
count is ``accept_lens - 1``, ranging 0..K-1).

RWKV-7's own linear-attention backend (``rwkv7_backend.py``) needed a small
addition to make the "reuse upstream verify" premise true: unlike
GDN/KDA/Lightning, RWKV bypasses the generic ``AttentionBackend.forward_extend``
dispatch entirely (the model calls ``token_shift``/``recurrence`` directly), so
none of the existing ``is_target_verify`` capture code applied. Fixed by adding
an ``is_target_verify`` branch there: K sequential calls to the same in-place
decode-shaped kernel used by plain decode, capturing each step's state into
``intermediate_ssm``/``intermediate_conv_window`` for the (already-generic)
``commit_mamba_states_after_verify`` to select from afterward.

Exact-by-construction at temperature 0: only tokens the target would greedily
emit are committed. Registered as the plugin algorithm ``RWKV_SPEC``; run with
``--disable-overlap-schedule`` (the recurrent verify is a synchronous V2 path).

Status: Strategy B build, iterated on the tower main container. The earlier
self-contained "Strategy A" implementation (manual snapshot/restore + a
re-run-the-accepted-prefix commit, no upstream verify reuse) is kept below,
renamed and unwired, as a fallback reference in case the backend addition
above hits a wall — see the block comment before it.

Speed (ADR-0006 (ii)): the draft's own K-1 step decode loop now runs through
a hand-rolled, self-contained CUDA graph (see the "draft decode CUDA graph"
section below), NOT sglang's shared ``DecodeCudaGraphRunner`` -- that class
hardcodes ``capture_forward_mode=TARGET_VERIFY`` for any draft worker under
any speculative algorithm (an EAGLE-family assumption incompatible with a
plain recurrent per-step draft) and is deliberately left untouched (shared,
high-blast-radius file). The custom graph lives entirely in this file, is
built lazily on first use, and falls back to the pre-existing eager path
(unchanged) on any capture failure or via ``RWKV_SPEC_DRAFT_GRAPH=0``.
"""

import logging
from typing import List, Optional

import torch

from sglang.srt.server_args import ServerArgs
from sglang.srt.speculative.base_spec_worker import BaseSpecWorker
from sglang.srt.speculative.spec_info import SpeculativeAlgorithm
from sglang.srt.speculative.spec_registry import CustomSpecAlgo

logger = logging.getLogger(__name__)

def _shared_graph_pool(worker):
    # One memory pool for EVERY manual capture this worker owns (draft step +
    # all verify-K variants). Separate private pools per capture is the
    # documented sharp edge behind rare cross-graph aliasing; sharing one pool
    # makes later captures allocate on top of earlier graphs' reservations
    # instead of interleaving with live allocations.
    pool = getattr(worker, "_graph_mem_pool", None)
    if pool is None:
        pool = torch.cuda.graph_pool_handle()
        worker._graph_mem_pool = pool
    return pool


def _adaptive_enabled() -> bool:
    import os

    return os.environ.get("RWKV_SPEC_ADAPTIVE", "0") == "1"



class RwkvSpecAlgo(CustomSpecAlgo):
    """Plugin descriptor: a recurrent draft with NO draft KV cache (like NGRAM),
    so the KV reserve must not be inflated for a draft-KV path."""

    def has_draft_kv(self) -> bool:
        return False

    def carries_draft_hidden_states(self) -> bool:
        # The recurrent draft is a separate model with its own O(1) state; it
        # does not hand hidden states to the target across a P/D boundary
        # (that is an EAGLE-family notion). Not in CustomSpecAlgo's defaults.
        return False

    def create_future_map(self, device, req_to_token_pool, needs_cpu_seq_lens=True):
        # Mirror SpeculativeAlgorithm.create_future_map (also absent from
        # CustomSpecAlgo). init_overlap constructs it unconditionally; the sync
        # (--disable-overlap-schedule) forward path we run does not consume it.
        from sglang.srt.managers.overlap_utils import FutureMap

        return FutureMap(device, self, req_to_token_pool, needs_cpu_seq_lens)


def _validate_server_args(server_args: ServerArgs) -> None:
    if not server_args.speculative_draft_model_path:
        raise ValueError(
            "RWKV_SPEC needs --speculative-draft-model-path <0.1B RWKV-7 dir>."
        )
    if not server_args.disable_overlap_schedule:
        # create_worker also guards this; make the message actionable early.
        raise ValueError("RWKV_SPEC requires --disable-overlap-schedule (V2 sync path).")


@SpeculativeAlgorithm.register(
    "RWKV_SPEC",
    supports_overlap=False,
    validate_server_args=_validate_server_args,
    spec_class=RwkvSpecAlgo,
)
def _rwkv_spec_factory(server_args: ServerArgs):
    # Lazy: importing the worker class pulls in TpModelWorker/ScheduleBatch/etc.,
    # which must NOT happen at plugin-registration (import) time (circular).
    return RwkvSpecWorker


# --------------------------------------------------------------------------- #
# The worker
# --------------------------------------------------------------------------- #


class RwkvSpecWorker(BaseSpecWorker):
    """Recurrent draft-glue spec worker (BaseSpecWorker surface, NGRAM-shaped).

    Subclassing BaseSpecWorker inherits no-op init_attention_backends /
    init_cuda_graphs / on_verify_complete_cpu / activate_step_by_batch — exactly
    right for an eager recurrent draft (no separate attn backend, no draft
    graphs yet). target_worker / draft_worker / clear_cache_pool are the
    abstract methods we implement.

    The scheduler sets ``self.model_worker = draft_worker`` and drives
    ``forward_batch_generation(batch)`` each step on the non-overlap V2 path.
    """

    def __init__(
        self,
        server_args: ServerArgs,
        gpu_id: int,
        tp_rank: int,
        dp_rank: Optional[int],
        moe_ep_rank: int,
        attn_cp_rank: int,
        moe_dp_rank: int,
        nccl_port: int,
        target_worker,
    ):
        from sglang.srt.managers.tp_worker import TpModelWorker

        self.server_args = server_args
        self._target_worker = target_worker
        self.target_runner = target_worker.model_runner
        self.device = f"cuda:{gpu_id}" if gpu_id >= 0 else "cuda"
        # K = the verify window width (== speculative_num_draft_tokens). Chain
        # position 0 is `t_last` (free accept, not a guess -- see module
        # docstring), so the draft only runs K-1 real decode steps per round.
        self.k = int(server_args.speculative_num_draft_tokens or 4)
        self.speculative_num_draft_tokens = self.k

        # Concurrency limit, enforced per round in _verify_round rather than
        # here: this worker drives ONE request's chain at a time (the snapshot
        # buffers, the hand-rolled draft/verify graphs and the rollback
        # bookkeeping are all bs=1 and worker-shared — grep "bs=1" in this
        # file), but `max_running_requests` is a capacity, not a promise that
        # the capacity gets used, and every working single-stream deployment we
        # have passes 32. Checking capacity would reject configurations that
        # are fine; checking the actual batch catches exactly the broken case.

        # The draft loads speculative_draft_model_path (TpModelWorker resolves it
        # via is_draft_worker). Force its context to the target's. Keep the
        # DRAFT'S OWN TpModelWorker built with disable_cuda_graph=True always —
        # this only opts it out of sglang's *generic* DecodeCudaGraphRunner,
        # which hardcodes capture_forward_mode=TARGET_VERIFY for ANY draft
        # worker under ANY speculative algorithm (model_executor/runner/
        # decode_cuda_graph_runner.py ~L249-253), an EAGLE-shaped assumption
        # our plain recurrent per-step draft doesn't match — RuntimeError(
        # "This should not happen") since RwkvSpecAlgo doesn't (and
        # semantically shouldn't) implement supports_target_verify_for_draft.
        # Speed instead comes from a SEPARATE, hand-rolled CUDA graph owned by
        # this file (see "draft decode CUDA graph" below) that captures the
        # draft's own ForwardMode.DECODE K-1 step loop directly via
        # torch.cuda.graph(), bypassing ModelRunner.init_cuda_graphs/
        # DecodeCudaGraphRunner entirely — so this disable_cuda_graph=True
        # stays exactly as it was (still correctly opting out of the shared,
        # incompatible generic mechanism).
        server_args.context_length = self.target_runner.model_config.context_len
        with _preserve(server_args, "disable_cuda_graph", True):
            self._draft = TpModelWorker(
                server_args=server_args,
                gpu_id=gpu_id,
                tp_rank=tp_rank,
                pp_rank=0,
                dp_rank=dp_rank,
                moe_ep_rank=moe_ep_rank,
                attn_cp_rank=attn_cp_rank,
                moe_dp_rank=moe_dp_rank,
                nccl_port=nccl_port,
                is_draft_worker=True,
            )
        self.draft_runner = self._draft.model_runner

        d_cfg = self.draft_runner.model_config.hf_config
        t_cfg = self.target_runner.model_config.hf_config
        self.draft_layers = list(range(d_cfg.num_hidden_layers))
        self.target_layers = list(range(t_cfg.num_hidden_layers))
        self._draft_slot = {}  # rid -> draft pool req index
        self._draft_shim = {}  # rid -> shim request object (owns draft pool bindings)
        # rids seen in the last decode round; used to release draft slots for
        # requests that left the batch (finished) — mirrors NGRAMWorker's
        # _prev_decode_rids, since req.finished() at the time we run is only
        # current through the PREVIOUS round (this round's accept isn't
        # applied to req.output_ids until after we return).
        self._prev_decode_rids: set = set()
        self._rounds = 0
        self._accept_sum = 0
        # Draft decode CUDA graph (ADR-0006 (ii), speed): built lazily on the
        # first real decode round (needs a live batch/req template + an
        # already-allocated draft pool). None until built; _draft_graph_failed
        # latches permanently true after any capture failure so we don't retry
        # every round. See _ensure_draft_decode_graph / _build_draft_decode_graph.
        self._draft_graph = None
        self._draft_graph_io = None
        self._draft_graph_failed = False
        self._graph_scratch_shim = None
        logger.info(
            "RWKV_SPEC up: draft=%s K=%d (Strategy B, --disable-overlap-schedule, "
            "draft-decode-graph=%s)",
            server_args.speculative_draft_model_path,
            self.k,
            "lazy" if self._draft_graph_enabled() else "off (RWKV_SPEC_DRAFT_GRAPH=0)",
        )

    # ---- BaseSpecWorker surface -------------------------------------------- #

    def alloc_memory_pool(
        self,
        memory_pool_config=None,
        req_to_token_pool=None,
        token_to_kv_pool_allocator=None,
    ):
        # Target pools exist by the time the scheduler calls this; keep refs.
        # The draft builds its OWN fresh pool (req_to_token_pool=None) so its
        # recurrent state never aliases the target's — but is_draft_worker does
        # not self-profile, so it needs the scheduler-sized memory_pool_config.
        self.req_to_token_pool, self.token_to_kv_pool_allocator = (
            self._target_worker.get_memory_pool()
        )
        self._draft.alloc_memory_pool(
            memory_pool_config=memory_pool_config,
            req_to_token_pool=None,
            token_to_kv_pool_allocator=None,
        )
        self.draft_pool = self.draft_runner.req_to_token_pool
        self.target_pool = self.target_runner.req_to_token_pool

    @property
    def model_runner(self):  # scheduler reads draft_worker.model_runner.*
        return self.draft_runner

    @property
    def target_worker(self):
        return self._target_worker

    @property
    def draft_worker(self):
        # Not an EagleDraftWorker — we own the (recurrent) draft ourselves.
        return None

    def clear_cache_pool(self):
        self._draft_slot.clear()
        self._draft_shim.clear()
        self._prev_decode_rids = set()

    def update_weights_from_tensor(self, recv_req):
        return self._target_worker.update_weights_from_tensor(recv_req)

    def init_attention_backends(self):
        # Same story as init_cuda_graphs below: the inherited no-op assumed
        # nothing needed setting up here, but the draft's own ModelRunner.
        # attn_backend is None until this runs (tower-confirmed: eager_runner's
        # _execute_extend reads model_runner.attn_backend directly).
        self._draft.init_attention_backends()

    def init_cuda_graphs(self):
        # BaseSpecWorker's inherited no-op assumed an eager recurrent draft
        # needs nothing here; tower-confirmed wrong: ModelRunner.init_cuda_graphs
        # unconditionally builds `self.eager_runner` (the EagerRunner used by
        # the plain-forward path _draft_extend/_draft_decode_one_logits go
        # through), even when it will never actually capture a graph. Mirrors
        # the pattern other draft-worker base classes use, but through `self.
        # _draft` (our own TpModelWorker) rather than the `draft_worker`
        # property, which we return None for on purpose (see the property
        # above) -- calling capture_decode_cuda_graph=False since the draft
        # was constructed with disable_cuda_graph=True (never captures for
        # real; this call exists purely for the eager_runner side effect).
        # Tried capture_decode_cuda_graph=True as the ADR-0006 (ii) speed
        # lever and reverted it -- see the __init__ comment above for why.
        self._draft.init_cuda_graphs(capture_decode_cuda_graph=False)

    # ---- the V2 entry point ------------------------------------------------ #

    def forward_batch_generation(self, batch, on_publish=None):
        if not batch.forward_mode.is_decode():
            # Extend/prefill: target runs normally; mirror the chunk into the
            # draft's own state so the round invariant holds at first decode.
            batch_result = self._target_worker.forward_batch_generation(batch)
            self._mirror_prefill_into_draft(batch)
            # Merge-safety contract (mirrors NGRAMWorker's prefill return): the
            # non-overlap spec scheduler assigns batch.spec_info from this
            # result, and ScheduleBatch.merge_batch calls
            # running.spec_info.merge_batch(prefill.spec_info) when a freshly
            # prefilled request joins an active decode batch. A None here dies
            # inside NgramVerifyInput.merge_batch -- latent until requests
            # actually overlap, which sequential gate runs never exercised.
            from sglang.srt.speculative.ngram_info import NgramVerifyInput

            bs = len(batch.reqs)
            predict = batch_result.next_token_ids
            accept_lens = torch.ones(bs, dtype=torch.int32, device=predict.device)
            accept_tokens = torch.zeros(
                bs, self.k, dtype=torch.int32, device=predict.device
            )
            accept_tokens[:, 0] = predict
            new_seq_lens = batch.seq_lens.clone()
            batch_result.next_draft_input = NgramVerifyInput(
                draft_token_num=self.k,
                new_seq_lens=new_seq_lens,
                accept_tokens=accept_tokens.flatten(),
                accept_lens=accept_lens,
            )
            batch_result.accept_lens = accept_lens
            batch_result.new_seq_lens = new_seq_lens
            batch_result.speculative_num_draft_tokens = self.k
            return batch_result

        return self._verify_round(batch, on_publish)

    # ---- prefill mirror ---------------------------------------------------- #

    def _mirror_prefill_into_draft(self, batch):
        """Run the same prompt chunk through the draft so both models have
        consumed the prompt (radix off)."""
        for req in batch.reqs:
            # NOTE: keyed off `prefix_indices` (the radix-cache hit length), NOT
            # `extend_range` — this is a hard invariant check ("radix must be off"),
            # independent of chunked-prefill bookkeeping below.
            radix_prefix_len = (
                len(req.prefix_indices) if req.prefix_indices is not None else 0
            )
            if req.rid not in self._draft_slot:
                if radix_prefix_len != 0:
                    raise RuntimeError(
                        "RWKV_SPEC: radix prefix hit on an unseen request — run with "
                        "--disable-radix-cache."
                    )
                self._ensure_draft_slot(req)
            # `Req.fill_ids` doesn't exist on current main; `get_fill_ids()` returns
            # `full_untruncated_fill_ids[:extend_range.end]`. Slice by
            # `extend_range.start:end` (the chunk THIS call actually extended), not
            # by `radix_prefix_len` — with radix off, `prefix_indices` stays empty
            # across chunked-prefill continuations of the same request, so slicing
            # by it would re-feed the whole accumulated prompt into the draft on
            # every chunk after the first.
            chunk_start = req.extend_range.start
            chunk = list(req.get_fill_ids()[chunk_start : req.extend_range.end])
            if chunk:
                self._draft_extend(batch, req, chunk, chunk_start)

    # ---- Strategy B: draft-glue + reuse upstream verify -------------------- #

    def _verify_round(self, batch, on_publish):
        import os as _os
        import time as _time

        # One request per round, by construction (see __init__). Past this point
        # every buffer is bs=1 and worker-shared, so a batch of 2+ walks off the
        # end of the snapshot stack and the process dies on an asynchronous
        # illegal memory access at whatever sync point comes next — the failure
        # F0077 attributed to adaptive K, which a 240-request concurrent soak
        # reproduces with a fixed chain length too. Refusing here turns a
        # corrupt-then-crash into a message that says what to do.
        _bs = len(getattr(batch, "reqs", ()) or ())
        if _bs > 1:
            raise NotImplementedError(
                f"RWKV_SPEC got a verify batch of {_bs} requests, but the chain "
                "machinery is single-request (bs=1 snapshot buffers and CUDA "
                "graphs, shared across the worker). Drive one request at a time, "
                "or launch without --speculative-algorithm RWKV_SPEC. Batching "
                "the draft chain is tracked as follow-up work. (F0078)"
            )

        _timing = _os.environ.get("RWKV_SPEC_TIMING", "0") == "1"

        def _mark(phase, t0):
            if not _timing:
                return 0.0
            torch.cuda.synchronize()
            now = _time.perf_counter()
            acc = getattr(self, "_t_acc", None)
            if acc is None:
                acc = {}
                self._t_acc = acc
                self._t_rounds = 0
            acc[phase] = acc.get(phase, 0.0) + (now - t0)
            return now

        t0 = 0.0
        if _timing:
            torch.cuda.synchronize()
            t0 = _time.perf_counter()
            last_exit = getattr(self, "_t_last_exit", None)
            if last_exit is not None and (t0 - last_exit) < 0.2:
                # gaps above 200 ms are idle time between requests, not
                # per-round scheduler glue -- exclude them from the average
                acc = getattr(self, "_t_acc", None)
                if acc is None:
                    acc = {}
                    self._t_acc = acc
                    self._t_rounds = 0
                acc["scheduler_gap"] = acc.get("scheduler_gap", 0.0) + (t0 - last_exit)
        from sglang.srt.managers.scheduler import GenerationBatchResult
        from sglang.srt.model_executor.forward_batch_info import (
            CaptureHiddenMode,
            ForwardMode,
        )
        from sglang.srt.speculative.eagle_utils import eagle_sample
        from sglang.srt.speculative.ngram_info import NgramVerifyInput
        from sglang.srt.speculative.spec_utils import (
            commit_mamba_states_after_verify,
            move_accept_tokens_to_target_kvcache,
            prepare_mamba_track_for_verify,
        )
        from sglang.srt.speculative.triton_ops.cache_locs import (
            assign_extend_cache_locs_func,
        )
        from sglang.srt.layers.attention.mamba.mamba_state_scatter_triton import (
            fused_conv_window_scatter_with_mask,
        )

        bs = len(batch.reqs)
        K = self.k
        # Adaptive K (RWKV_SPEC_ADAPTIVE=1, bs=1): pick this round's chain
        # length from the request's recent accept EMA. High-accept workloads
        # (math/code) run K=8 and keep their 2.4x; low-accept prose drops to
        # K=4 rather than burning draft steps that will be rejected. Server K
        # is the CAPACITY (buffers, pool windows); the per-round k only
        # shrinks it, never exceeds.
        # EXPERIMENTAL, default OFF: with adaptive K the multi-K verify-graph
        # path dies within a few requests on an async illegal memory access
        # (fixed-K runs are 40+ requests clean; upfront capture and a shared
        # graph memory pool were both tried and neither cured it). Gate is
        # 10/10 and the K distribution verifiably switches while it lives,
        # so the logic is right and the race is in the multi-graph replay
        # path. Needs a compute-sanitizer racecheck session before this can
        # default on.
        if (
            bs == 1
            and _os.environ.get("RWKV_SPEC_ADAPTIVE", "0") == "1"
        ):
            ema_map = getattr(self, "_accept_ema", None)
            if ema_map is None:
                ema_map = {}
                self._accept_ema = ema_map
            ema = ema_map.get(batch.reqs[0].rid, 3.0)
            K = 8 if ema >= 4.2 else (6 if ema >= 2.1 else 4)
            K = min(K, self.k)
            kd = getattr(self, "_k_dist", None)
            if kd is None:
                kd = {}
                self._k_dist = kd
            kd[K] = kd.get(K, 0) + 1
            if sum(kd.values()) % 200 == 0:
                logger.info("RWKV_SPEC adaptive K distribution: %s", dict(sorted(kd.items())))
        dev = batch.seq_lens.device

        # 1) draft proposes K-1 tokens per request; position 0 of the verify
        #    chain is `t_last` itself (see module docstring for why).
        all_tokens: List[int] = []
        snaps_per_req = []
        for req in batch.reqs:
            t_last = req.output_ids[-1] if req.output_ids else req.origin_input_ids[-1]
            drafts, snaps = self._draft_decode_chain(batch, req, t_last, K)
            all_tokens.append(t_last)
            all_tokens.extend(drafts)
            snaps_per_req.append(snaps)

        t0 = _mark("draft", t0)

        draft_token = torch.tensor(all_tokens, dtype=torch.int64, device=dev)

        # 2) chain verify-input: topk=1 linear chain, no branching. Real
        #    tensors required here, NOT None — verify_tree_greedy_func passes
        #    retrieve_next_token/sibling straight into the compiled kernel
        #    with no None fast-path (checked directly, not assumed).
        idx = torch.arange(bs * K, device=dev, dtype=torch.int64).view(bs, K)
        retrieve_index = idx
        retrieve_next_token = torch.cat(
            [idx[:, 1:], torch.full((bs, 1), -1, dtype=torch.int64, device=dev)],
            dim=1,
        )
        retrieve_next_sibling = torch.full((bs, K), -1, dtype=torch.int64, device=dev)
        # position 0 (t_last) is already-committed -> its absolute position is
        # seq_lens-1; positions 1..K-1 are the new chain steps after it. RWKV's
        # own recurrence doesn't consume absolute positions (no RoPE), so this
        # is generic-bookkeeping-correct rather than load-bearing.
        positions = (
            (batch.seq_lens - 1).unsqueeze(1) + torch.arange(K, device=dev).unsqueeze(0)
        ).flatten()
        # RWKV's backend never reads an attention mask (bypasses the generic
        # forward_extend dispatch entirely); this only needs to be a validly
        # shaped/deviced tensor for NgramVerifyInput's own bookkeeping.
        custom_mask = torch.ones(bs * K, dtype=torch.bool, device=dev)

        batch.forward_mode = ForwardMode.TARGET_VERIFY
        batch.input_ids = draft_token
        batch.out_cache_loc = assign_extend_cache_locs_func(
            req_pool_indices=batch.req_pool_indices,
            req_to_token=batch.req_to_token_pool.req_to_token,
            start_offset=batch.seq_lens,
            end_offset=batch.seq_lens + K,
            batch_size=bs,
            draft_token_num=K,
            device=dev,
        )
        prepare_mamba_track_for_verify(batch)
        batch.spec_info = NgramVerifyInput(
            draft_token=draft_token,
            custom_mask=custom_mask,
            positions=positions,
            retrieve_index=retrieve_index,
            retrieve_next_token=retrieve_next_token,
            retrieve_next_sibling=retrieve_next_sibling,
            draft_token_num=K,
        )
        # Request raw hidden states so we can recompute logits ourselves below
        # (NgramVerifyInput doesn't take this in its constructor; ForwardBatch.
        # init_new reads it via getattr with a NULL default).
        batch.spec_info.capture_hidden_mode = CaptureHiddenMode.FULL

        t0 = _mark("prep", t0)

        # 3) reuse upstream verify + commit — the whole point of Strategy B.
        #    Graphed when possible: the eager TARGET_VERIFY forward is the
        #    round's dominant cost (launch-bound small kernels), and the
        #    capture-replay idiom is the same one the draft graph already
        #    proved. The real per-round spec_info above still feeds
        #    eagle_sample/commit below either way.
        use_vgraph = (
            bs == 1
            and not getattr(batch, "return_logprob", False)
            and self._ensure_verify_graph(batch, K)
        )
        if not getattr(self, "_vpath_logged", False):
            self._vpath_logged = True
            logger.info("RWKV_SPEC verify path this run: %s", "GRAPH" if use_vgraph else "EAGER")
        if use_vgraph:
            io = self._verify_graphs.get(K)
            if io is None:
                # Defensive: _ensure_verify_graph said yes but the entry is
                # absent -- log the evidence loudly and take the eager path
                # instead of killing the scheduler. (One unexplained KeyError
                # was observed here; if this fires again the keys tell why.)
                logger.warning(
                    "RWKV_SPEC: verify graph for k=%d missing (have %s) -- eager",
                    K,
                    sorted(self._verify_graphs.keys()),
                )
                use_vgraph = False
        if use_vgraph:
            io["req_pool_indices"].copy_(batch.req_pool_indices)
            io["seq_lens"].copy_(batch.seq_lens)
            io["input_ids"].copy_(draft_token)
            io["positions"].copy_(positions)
            io["out_cache_loc"].copy_(batch.out_cache_loc)
            io["graph"].replay()
            logits_output = io["out"].logits_output
            verify_can_run_cuda_graph = False
        else:
            batch_result = self._target_worker.forward_batch_generation(
                batch, is_verify=True
            )
            logits_output = batch_result.logits_output
            verify_can_run_cuda_graph = batch_result.can_run_cuda_graph
        t0 = _mark("target_fwd", t0)
        # The generic LogitsProcessor projects all bs*K verify rows through ONE
        # batched matmul; cuBLAS's reduction order for that M-shape can differ
        # from the M=1 GEMV the plain decode baseline uses, flipping a near-tie
        # argmax (the exact F0031 class of bug, previously fixed in Strategy A
        # via this same per-row recompute). Overwrite next_token_logits with a
        # per-row [1,H]@[H,V] projection -- identical reduction order to M=1
        # decode -- before sampling, so verify and baseline agree bit-for-bit.
        # Skipped under RWKV_FAST_LMHEAD=1: the LogitsProcessor has then already
        # projected these rows through the shared-weight GEMV, which is bit-identical
        # per row to the M=1 projection plain decode used, so the invariance this
        # recompute exists to enforce is structural and repeating it re-reads a
        # 512 MiB weight for nothing. Measured 1.90 ms/round at M=6 and linear in
        # bs*K, i.e. the single phase that would sink a batched chain (F0078).
        if _os.environ.get("RWKV_FAST_LMHEAD", "0") != "1":
            w = self.target_runner.model.lm_head.weight
            vocab = self.target_runner.model_config.vocab_size
            h = logits_output.hidden_states.to(w.dtype)
            logits_output.next_token_logits = torch.cat(
                [
                    torch.matmul(h[i : i + 1], w.t()).float()[:, :vocab]
                    for i in range(h.shape[0])
                ],
                dim=0,
            )
        t0 = _mark("head_recompute", t0)
        predict, accept_lens, accept_index = eagle_sample(
            batch.spec_info, batch, logits_output, None
        )
        new_seq_lens = batch.seq_lens + accept_lens
        commit_mamba_states_after_verify(
            self._target_worker, batch, accept_lens, accept_index, K
        )
        # accept_lens includes the free position-0 accept (t_last, not a real
        # draft); the real per-request draft accept count is accept_lens - 1,
        # ranging 0..K-1 — matches NGRAM's own num_correct_drafts_per_req. Also
        # exactly `last_correct_step_indices` for our linear (topk=1) chain
        # (verified against verify_tree_greedy_kernel_triton's node-0-is-free
        # walk, same derivation spec_utils.commit_mamba_states_after_verify
        # uses internally).
        num_correct_drafts = accept_lens - 1
        # RWKV-7 has TWO token-shifts per layer (attention conv[0] + FFN
        # conv[1]); commit_mamba_states_after_verify's generic scatter above is
        # hardcoded to conv[0]/intermediate_conv_window[0] (hybrid_linear_attn_
        # backend.py) because every other linear-attn backend it was written
        # for (GDN/KDA/Lightning) has only one conv. Not something to patch in
        # that shared file for one backend's shape -- do the same scatter here
        # for index 1, reusing the exact indices the generic call derived.
        mamba_caches = (
            self.target_runner.attn_backend.linear_attn_backend.req_to_token_pool.get_speculative_mamba2_params_all_layers()
        )
        state_indices_tensor = (
            self.target_runner.attn_backend.linear_attn_backend.forward_metadata.mamba_cache_indices[
                :bs
            ]
        )
        fused_conv_window_scatter_with_mask(
            mamba_caches.conv[1],
            mamba_caches.intermediate_conv_window[1],
            state_indices_tensor,
            num_correct_drafts,
        )
        accept_tokens = predict[accept_index].flatten()
        next_token_ids = accept_tokens
        move_accept_tokens_to_target_kvcache(
            batch, accept_index, num_correct_drafts, self.token_to_kv_pool_allocator
        )

        t0 = _mark("sample_commit", t0)

        # 4) NEW: roll back the draft's own state to the accepted length
        #    (checkpoint-and-commit — the one genuinely new piece of logic
        #    here; the target's rollback above is upstream's, for free).
        num_correct_drafts_cpu = num_correct_drafts.tolist()
        ema_map = getattr(self, "_accept_ema", None)
        for i, req in enumerate(batch.reqs):
            self._commit_draft_rollback(snaps_per_req[i], num_correct_drafts_cpu[i])
            self._rounds += 1
            accepted = num_correct_drafts_cpu[i] + 1
            self._accept_sum += accepted
            if ema_map is not None:
                prev = ema_map.get(req.rid, 3.0)
                ema_map[req.rid] = 0.7 * prev + 0.3 * accepted

        cur_rids = {req.rid for req in batch.reqs}
        departed_rids = self._prev_decode_rids - cur_rids
        for rid in departed_rids:
            self._release_draft_slot_by_rid(rid)
        self._prev_decode_rids = cur_rids

        if on_publish is not None:
            on_publish(new_seq_lens)

        t0 = _mark("rollback_glue", t0)
        if _timing:
            self._t_last_exit = _time.perf_counter()
            self._t_rounds += 1
            if self._t_rounds % 50 == 0:
                total = sum(self._t_acc.values())
                parts = "  ".join(
                    f"{k}={v * 1000 / self._t_rounds:.2f}ms({v / total * 100:.0f}%)"
                    for k, v in sorted(self._t_acc.items(), key=lambda kv: -kv[1])
                )
                logger.info(
                    "RWKV_SPEC timing over %d rounds: total %.2f ms/round | %s",
                    self._t_rounds,
                    total * 1000 / self._t_rounds,
                    parts,
                )

        next_draft_input = NgramVerifyInput(
            draft_token_num=K,
            new_seq_lens=new_seq_lens,
            accept_tokens=accept_tokens,
            accept_lens=accept_lens,
        )
        return GenerationBatchResult(
            logits_output=logits_output,
            next_token_ids=next_token_ids,
            can_run_cuda_graph=verify_can_run_cuda_graph,
            accept_lens=accept_lens,
            new_seq_lens=new_seq_lens,
            next_draft_input=next_draft_input,
            speculative_num_draft_tokens=K,
            num_correct_drafts_per_req_cpu=num_correct_drafts_cpu,
        )

    def _draft_decode_chain(self, batch, req, t_last, k=None) -> tuple:
        k = k if k is not None else self.k
        """K-1 greedy decode steps on the draft's own pool for ONE request.

        Returns (drafts: List[int] length K-1, snaps: list of K state
        snapshots — snaps[0] = before any draft step (== state as of t_last,
        the correct rollback target if 0 drafts are accepted), snaps[j] for
        j>=1 = after j draft steps).
        """
        draft_req_idx = self._draft_slot[req.rid]
        d_mslot = self._mamba_idx(self.draft_pool, draft_req_idx)
        cur_len = len(req.origin_input_ids) + len(req.output_ids)

        # Lazily build the draft-decode CUDA graph on first use (needs a live
        # batch/req as a one-time template — see _build_draft_decode_graph).
        # Cheap no-op check on every later round; permanently falls back to
        # the unchanged eager path (already gated 10/10) if capture ever
        # fails, so this can never regress correctness, only speed.
        use_graph = self._ensure_draft_decode_graph(batch, req)

        use_stacked = use_graph and len(batch.reqs) == 1
        if use_stacked:
            # Stacked snapshot buffers: one preallocated [K, L, ...] tensor per
            # state kind, written slice-by-slice -- per-layer copies without
            # clone allocations or torch.stack cats. Restore is the mirror
            # copy. bs=1 only: the buffers are worker-shared, and rollback
            # happens after ALL requests' chains, so a second request's chain
            # would overwrite the first's snapshots.
            bufs = getattr(self, "_snap_bufs", None)
            if bufs is None:
                pool = self.draft_pool
                caches = [pool.mamba2_layer_cache(lid) for lid in self.draft_layers]
                L = len(caches)
                c0 = caches[0]
                bufs = dict(
                    conv0=torch.empty(
                        (self.k, L) + tuple(c0.conv[0].shape[1:]),
                        dtype=c0.conv[0].dtype,
                        device=c0.conv[0].device,
                    ),
                    conv1=torch.empty(
                        (self.k, L) + tuple(c0.conv[1].shape[1:]),
                        dtype=c0.conv[1].dtype,
                        device=c0.conv[1].device,
                    ),
                    temporal=torch.empty(
                        (self.k, L) + tuple(c0.temporal.shape[1:]),
                        dtype=c0.temporal.dtype,
                        device=c0.temporal.device,
                    ),
                    caches=caches,
                )
                self._snap_bufs = bufs

            def _snap_into(j):
                for i, cache in enumerate(bufs["caches"]):
                    bufs["conv0"][j, i].copy_(cache.conv[0][d_mslot])
                    bufs["conv1"][j, i].copy_(cache.conv[1][d_mslot])
                    bufs["temporal"][j, i].copy_(cache.temporal[d_mslot])

            snaps = ("stacked", bufs, d_mslot)
        else:
            snaps = []
        if use_graph:
            pass
            # Chained replay with NO per-step host sync: each step's argmax is
            # computed on-GPU and copied straight into the graph's static
            # input buffer for the next replay (device-to-device, stream-
            # ordered). The eager path below still syncs per step -- that is
            # the gated fallback, unchanged. One .tolist() at the end fetches
            # the whole chain.
            io = self._draft_graph_io
            d_toks = getattr(self, "_d_toks", None)
            if d_toks is None or d_toks.numel() < self.k - 1:
                d_toks = torch.empty(
                    max(1, self.k - 1),
                    dtype=torch.int64,
                    device=self.draft_runner.device,
                )
                self._d_toks = d_toks
            io["req_pool_indices"].fill_(draft_req_idx)
            io["input_ids"].fill_(t_last)
            # K replays over cand=[t_last, d_0..d_{K-2}]: replay m consumes
            # cand[m]. Snapshot AFTER each replay, so snaps[m] = the state
            # having consumed cand[0..m] = (t_last, d_0..d_{m-1}) -- exactly
            # the rollback target when m drafts are accepted, for EVERY
            # m=0..K-1 including full accept. The previous scheme snapped
            # before the first replay and ran only K-1 replays: every
            # rollback (and even the full-accept no-op) left the draft state
            # one committed token short, permanently desyncing it. The gate
            # never noticed -- draft state only shapes proposals, never the
            # target's committed tokens -- but measured accept-length sat at
            # ~1.2 against an independently measured alpha of ~0.7. The K-th
            # replay's own prediction is unused; its STATE is the point.
            for step in range(k):
                ocl = self.draft_runner.token_to_kv_pool_allocator.alloc(1)
                io["seq_lens"].fill_(cur_len + step + 1)
                io["out_cache_loc"].copy_(ocl)
                self._draft_graph.replay()
                if use_stacked:
                    _snap_into(step)
                else:
                    snaps.append(
                        _snapshot(self.draft_pool, self.draft_layers, d_mslot)
                    )
                if step < k - 1:
                    logits = io["out"].logits_output.next_token_logits
                    d_toks[step : step + 1] = torch.argmax(logits, dim=-1)
                    io["input_ids"].copy_(d_toks[step : step + 1])
            drafts = [int(t) for t in d_toks[: k - 1].tolist()]
            return drafts, snaps
        drafts: List[int] = []
        tok = t_last
        for step in range(k):
            logits = self._draft_decode_one_logits(
                batch, req, draft_req_idx, tok, cur_len + step
            )
            # Same K-replay, post-forward snapshot ordering as the graphed
            # path above (the last step's prediction is unused; its state is
            # the full-accept rollback target).
            snaps.append(_snapshot(self.draft_pool, self.draft_layers, d_mslot))
            if step < k - 1:
                nxt = int(torch.argmax(logits, dim=-1))
                drafts.append(nxt)
                tok = nxt
        return drafts, snaps

    def _commit_draft_rollback(self, snaps, num_accepted):
        """Restore the draft's own recurrent state to the checkpoint matching
        exactly `num_accepted` (0..K-1) accepted draft steps. A no-op copy
        when num_accepted == K-1 (current state already matches)."""
        if isinstance(snaps, tuple) and snaps and snaps[0] == "stacked":
            _, bufs, slot = snaps
            for i, cache in enumerate(bufs["caches"]):
                cache.conv[0][slot].copy_(bufs["conv0"][num_accepted, i])
                cache.conv[1][slot].copy_(bufs["conv1"][num_accepted, i])
                cache.temporal[slot].copy_(bufs["temporal"][num_accepted, i])
            return
        _restore(self.draft_pool, self.draft_layers, snaps[num_accepted])

    # ---- draft pool slot mgmt --------------------------------------------- #

    def _ensure_draft_slot(self, req):
        import types

        shim = types.SimpleNamespace(
            rid=req.rid, req_pool_idx=None, mamba_pool_idx=None,
        )
        idx = self.draft_pool.alloc([shim])
        assert idx is not None, "draft state pool exhausted"
        self._draft_slot[req.rid] = int(idx[0])
        self._draft_shim[req.rid] = shim

    def _release_draft_slot_by_rid(self, rid):
        idx = self._draft_slot.pop(rid, None)
        shim = self._draft_shim.pop(rid, None)
        if idx is None or shim is None:
            return
        try:
            if getattr(shim, "mamba_pool_idx", None) is not None:
                self.draft_pool.free_mamba_cache(shim)
            self.draft_pool.free(shim)
        except Exception:
            logger.warning("draft slot %s free failed", idx, exc_info=True)

    def _mamba_idx(self, pool, req_pool_idx):
        return int(
            pool.get_mamba_indices(
                torch.tensor([req_pool_idx], dtype=torch.int64, device=pool.device)
            )[0]
        )

    # ---- ad-hoc single-request forwards (outside the scheduler's normal ---- #
    # ---- batch flow — the draft's own K-1 decode steps + prefill mirror) --- #

    def _draft_decode_one_logits(self, batch, req, draft_req_idx, token, cur_len):
        """One greedy decode step on the draft's own model+pool; returns
        next_token_logits [vocab] for a single request."""
        fb = self._build_forward(
            batch, self.draft_runner, req, draft_req_idx, [token], cur_len, extend=False
        )
        out = self.draft_runner.forward(fb)
        return out.logits_output.next_token_logits[0]

    # ---- draft decode CUDA graph (speed; ADR-0006 (ii)) --------------------- #
    #
    # sglang's shared, generic DecodeCudaGraphRunner hardcodes
    # capture_forward_mode=TARGET_VERIFY for ANY draft worker under ANY
    # speculative algorithm (decode_cuda_graph_runner.py ~L249-253) -- an
    # EAGLE-family assumption ("draft workers verify their own nested chain")
    # incompatible with our plain recurrent per-step draft, and deliberately
    # NOT patched here (shared file, blast radius far outside this task; the
    # attempt + revert is documented in project-spec-decode.md 2026-07-07).
    # Instead: a narrow, self-contained CUDA graph, owned entirely by this
    # file, used ONLY for the draft's own K-1 step ForwardMode.DECODE loop
    # (always bs=1/n=1 -- _verify_round drives one request's chain at a time).
    #
    # Standard PyTorch idiom (torch docs "CUDA Graphs"): pre-allocate static
    # leaf tensors, warm up on a side stream long enough to trigger any lazy
    # one-time setup inside the model (e.g. Rwkv7ChannelMix's M6 sparse-cmix
    # tiled-weight build, which lazily builds+caches on the first bsz1-fp16-
    # decode call), capture ONE call into a CUDAGraph, then on each later
    # replay only overwrite the static buffers' CONTENTS (never their
    # identity/address) and call graph.replay() -- the recorded kernels
    # re-read the fresh values.
    #
    # What's safe to bake into the static buffers vs. what must stay eager
    # (confirmed by reading hybrid_linear_attn_backend.py's _forward_metadata,
    # not assumed):
    #   - input_ids / seq_lens / req_pool_indices: pure data read by GPU ops
    #     inside the captured region -- e.g. get_mamba_indices(req_pool_
    #     indices) is a GPU gather over req_pool_indices's CURRENT contents,
    #     not a value baked in at capture time -- safe to mutate via .fill_()
    #     before every replay, including switching to a different request's
    #     pool slot between rounds.
    #   - out_cache_loc: comes from token_to_kv_pool_allocator.alloc(n), which
    #     does its own non-replayable bookkeeping -- this call MUST stay
    #     outside the graph, called eagerly every step exactly as the eager
    #     path already does, with its result copied into a static buffer that
    #     IS referenced inside the graph.
    #   - seq_lens_cpu: a plain .cpu() sync -- confirmed unread anywhere on
    #     the is_decode_or_idle() metadata path unless --enable-linear-
    #     replayssm is on (we don't turn that on), so it is set once at build
    #     time and never touched again. If some future change starts reading
    #     it, that would surface as a gate failure or a capture-time error,
    #     not a silent wrong answer.
    #   - forward_batch.reqs[0] / other non-tensor `batch`-level fields: baked
    #     in from whichever req/batch was passed to _build_draft_decode_graph
    #     at build time. Fine for this worker's current draft path (uniform
    #     config, no per-request LoRA on the draft) -- would need revisiting
    #     if the draft ever needs a non-tensor field that varies per round.
    #
    # Correctness is proven by the SAME hard gate as everything else in this
    # file (bench/spec_gate.py, spec-on == spec-off token-identical), not by
    # this comment -- falls back to the unchanged eager path (still gated
    # 10/10 on its own) on any capture-time failure, or via
    # RWKV_SPEC_DRAFT_GRAPH=0.

    def _draft_graph_enabled(self) -> bool:
        import os

        return os.environ.get("RWKV_SPEC_DRAFT_GRAPH", "1") != "0"

    # ---- target-verify CUDA graph (same idiom as the draft graph) ----------- #
    #
    # The TARGET_VERIFY forward is the round's dominant cost once the draft is
    # graphed: an eager 24-layer pass over K positions plus the backend's
    # K-step recurrence loop -- all small kernels, launch-bound. Same cure as
    # the draft: one hand-rolled, self-contained CUDA graph owned by this
    # file, capturing exactly `model_runner.forward(fb)` for the bs=1
    # TARGET_VERIFY shape. Everything with side effects that cannot replay
    # (assign_extend_cache_locs_func's req_to_token writes, mamba-track prep)
    # stays eager per round, feeding static buffers the graph reads.
    #
    # bs=1 only (matches the rest of this worker's chain design); falls back
    # permanently to the eager verify on any capture failure, or via
    # RWKV_SPEC_VERIFY_GRAPH=0, or per-round when return_logprob is requested
    # (the template bakes return_logprob=False).

    def _verify_graph_enabled(self) -> bool:
        import os

        return os.environ.get("RWKV_SPEC_VERIFY_GRAPH", "1") != "0"

    def _ensure_verify_graph(self, batch, k=None) -> bool:
        k = k if k is not None else self.k
        graphs = getattr(self, "_verify_graphs", None)
        if graphs is None:
            graphs = {}
            self._verify_graphs = graphs
        if k in graphs:
            return graphs[k] is not None
        if not self._verify_graph_enabled() or len(batch.reqs) != 1:
            graphs[k] = None
            return False
        try:
            # Capture every K variant up front on the first request, rather
            # than lazily mid-serving: each capture creates its own private
            # allocator pool, and interleaving new captures with live rounds
            # is exactly the kind of allocator-state interaction that showed
            # up as a rare async illegal-access. One place, one time.
            todo = [self.k]
            if _adaptive_enabled():
                todo = sorted({4, 6, 8, self.k} & set(range(1, self.k + 1)))
            for kk in todo:
                if kk not in graphs:
                    self._build_verify_graph(batch, kk)
                    logger.info(
                        "RWKV_SPEC: target-verify CUDA graph captured OK (k=%d)", kk
                    )
            if k not in graphs:
                self._build_verify_graph(batch, k)
                logger.info(
                    "RWKV_SPEC: target-verify CUDA graph captured OK (k=%d)", k
                )
            return True
        except Exception:
            logger.warning(
                "RWKV_SPEC: target-verify CUDA graph capture failed (k=%d) -- "
                "eager verify for this k from now on",
                k,
                exc_info=True,
            )
            graphs[k] = None
            return False

    def _build_verify_graph(self, batch, k=None) -> None:
        import dataclasses
        import types

        from sglang.srt.model_executor.forward_batch_info import (
            CaptureHiddenMode,
            ForwardBatch,
            ForwardMode,
        )
        from sglang.srt.speculative.ngram_info import NgramVerifyInput
        from sglang.srt.speculative.triton_ops.cache_locs import (
            assign_extend_cache_locs_func,
        )

        runner = self.target_runner
        dev = runner.device
        K = k if k is not None else self.k
        req = batch.reqs[0]

        # Dedicated scratch slot on the TARGET pool for warmup/capture practice
        # forwards, so they never touch a real request's recurrent state.
        pool = self.target_pool
        shim = types.SimpleNamespace(
            rid="__rwkv_spec_verify_graph_scratch__",
            req_pool_idx=None,
            mamba_pool_idx=None,
        )
        scratch_idx = int(pool.alloc([shim])[0])
        self._verify_scratch_shim = shim

        g_input_ids = torch.zeros(K, dtype=torch.int64, device=dev)
        g_positions = torch.zeros(K, dtype=torch.int64, device=dev)
        g_seq_lens = torch.zeros(1, dtype=torch.int64, device=dev)
        g_req_pool_indices = torch.full((1,), scratch_idx, dtype=torch.int64, device=dev)
        g_out_cache_loc = torch.zeros(K, dtype=torch.int64, device=dev)
        g_seq_lens_cpu_dummy = torch.zeros(1, dtype=torch.int64)

        # Chain-shape constants for bs=1: identical every round by construction
        # (see _verify_round), so they are baked as real tensors, not rebuilt.
        idx = torch.arange(K, device=dev, dtype=torch.int64).view(1, K)
        retrieve_next_token = torch.cat(
            [idx[:, 1:], torch.full((1, 1), -1, dtype=torch.int64, device=dev)], dim=1
        )
        retrieve_next_sibling = torch.full((1, K), -1, dtype=torch.int64, device=dev)
        custom_mask = torch.ones(K, dtype=torch.bool, device=dev)

        spec_info = NgramVerifyInput(
            draft_token=g_input_ids,
            custom_mask=custom_mask,
            positions=g_positions,
            retrieve_index=idx,
            retrieve_next_token=retrieve_next_token,
            retrieve_next_sibling=retrieve_next_sibling,
            draft_token_num=K,
        )
        spec_info.capture_hidden_mode = CaptureHiddenMode.FULL

        cur_len = len(req.origin_input_ids) + len(req.output_ids)

        def _one_verify(seq_len_val):
            g_seq_lens.fill_(seq_len_val)
            overrides = dict(
                reqs=[req],
                req_to_token_pool=runner.req_to_token_pool,
                token_to_kv_pool_allocator=runner.token_to_kv_pool_allocator,
                req_pool_indices=g_req_pool_indices,
                input_ids=g_input_ids,
                seq_lens=g_seq_lens,
                seq_lens_sum=int(seq_len_val),
                seq_lens_cpu=g_seq_lens_cpu_dummy,
                out_cache_loc=g_out_cache_loc,
                forward_mode=ForwardMode.TARGET_VERIFY,
                spec_info=spec_info,
                sampling_info=None,
                capture_hidden_mode=None,
                return_hidden_states_before_norm=False,
                return_logprob=False,
                top_logprobs_nums=[0],
                token_ids_logprobs=[None],
            )
            verify_batch = dataclasses.replace(batch, **overrides)
            fb = ForwardBatch.init_new(verify_batch, runner)
            return runner.forward(fb)

        # Eagerly seed out_cache_loc/req_to_token for the scratch slot the way
        # every real round does, so warmup/capture see the true code path.
        def _seed_cache_locs(seq_len_val):
            locs = assign_extend_cache_locs_func(
                req_pool_indices=g_req_pool_indices,
                req_to_token=runner.req_to_token_pool.req_to_token,
                start_offset=g_seq_lens,
                end_offset=g_seq_lens + K,
                batch_size=1,
                draft_token_num=K,
                device=dev,
            )
            g_out_cache_loc.copy_(locs)

        warmup_stream = torch.cuda.Stream()
        warmup_stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(warmup_stream):
            for i in range(5):
                g_seq_lens.fill_(cur_len + 1 + i)
                _seed_cache_locs(cur_len + 1 + i)
                _one_verify(cur_len + 1 + i)
        torch.cuda.current_stream().wait_stream(warmup_stream)

        g = torch.cuda.CUDAGraph()
        g_seq_lens.fill_(cur_len + 6)
        _seed_cache_locs(cur_len + 6)
        with torch.cuda.graph(g, pool=_shared_graph_pool(self)):
            static_out = _one_verify(cur_len + 6)

        self._verify_graphs[K] = dict(
            graph=g,
            input_ids=g_input_ids,
            positions=g_positions,
            seq_lens=g_seq_lens,
            req_pool_indices=g_req_pool_indices,
            out_cache_loc=g_out_cache_loc,
            out=static_out,
        )
        # Return the scratch slot: replay reads req_pool_indices' CONTENTS, so
        # the scratch row is only ever touched during warmup/capture. Holding
        # it would trip the scheduler's idle-time req_to_token_pool leak check
        # (all-slots-free invariant) after the first request completes.
        try:
            if getattr(shim, "mamba_pool_idx", None) is not None:
                pool.free_mamba_cache(shim)
            pool.free(shim)
        except Exception:
            logger.warning(
                "RWKV_SPEC: verify-graph scratch slot free failed", exc_info=True
            )
        self._verify_scratch_shim = None

    def _ensure_draft_decode_graph(self, batch, req) -> bool:
        """Lazily build (once) the bs=1/n=1 DECODE-mode CUDA graph for the
        draft's own per-step forward. Returns True iff the graph is ready to
        use. No-op cost on every later round (single attribute check);
        permanently False after a failed attempt (never retries mid-run)."""
        if self._draft_graph is not None:
            return True
        if self._draft_graph_failed:
            return False
        if not self._draft_graph_enabled():
            self._draft_graph_failed = True
            return False
        try:
            self._build_draft_decode_graph(batch, req)
            logger.info("RWKV_SPEC: draft decode CUDA graph captured OK")
            return True
        except Exception:
            logger.warning(
                "RWKV_SPEC: draft decode CUDA graph capture failed -- falling "
                "back to eager draft decode for the rest of this run",
                exc_info=True,
            )
            self._draft_graph = None
            self._draft_graph_io = None
            self._draft_graph_failed = True
            return False

    def _build_draft_decode_graph(self, batch, req) -> None:
        """One-time capture. `batch`/`req` are only a TEMPLATE (their tensor
        fields get overridden with static buffers below; only non-tensor
        fields like dtype/model_config/tree_cache carry through as-is, same
        as _build_forward already relies on for the eager path)."""
        import dataclasses
        import types

        from sglang.srt.model_executor.forward_batch_info import (
            ForwardBatch,
            ForwardMode,
        )

        runner = self.draft_runner
        dev = runner.device

        # Dedicated scratch mamba slot for warmup+capture ONLY -- never used
        # by a real request, so the "practice" forward calls below (whose
        # logits/state are discarded) cannot perturb any real request's
        # recurrent state. Held for the worker's lifetime, never freed.
        shim = types.SimpleNamespace(
            rid="__rwkv_spec_draft_graph_scratch__",
            req_pool_idx=None,
            mamba_pool_idx=None,
        )
        scratch_idx = int(self.draft_pool.alloc([shim])[0])
        self._graph_scratch_shim = shim  # keep alive (pool may key off identity)

        g_input_ids = torch.zeros(1, dtype=torch.int64, device=dev)
        g_req_pool_indices = torch.full(
            (1,), scratch_idx, dtype=torch.int64, device=dev
        )
        g_seq_lens = torch.zeros(1, dtype=torch.int64, device=dev)

        # Probe out_cache_loc's shape from a real allocator call (the same
        # call the eager path already makes every step) before sizing the
        # static buffer that will alias it inside the graph -- don't assume.
        probe = runner.token_to_kv_pool_allocator.alloc(1)
        assert probe is not None and probe.numel() == 1, (
            "RWKV_SPEC draft graph: expected token_to_kv_pool_allocator.alloc(1) "
            f"to return exactly one slot per token, got "
            f"{None if probe is None else tuple(probe.shape)} -- refusing to "
            "build a graph on an unverified assumption."
        )
        g_out_cache_loc = torch.zeros_like(probe)
        g_out_cache_loc.copy_(probe)
        # seq_lens_cpu must NOT be derived via a fresh .cpu() sync inside
        # _one_step: that is a CPU<->CUDA copy, and CUDA graph capture
        # explicitly forbids unpinned host copies during capture (confirmed
        # empirically -- capture raised "Cannot copy between CPU and CUDA
        # tensors during CUDA graph capture unless the CPU tensor is pinned").
        # Use one fixed, plain CPU tensor instead: the is_decode_or_idle()
        # metadata path only reads seq_lens_cpu behind the (disabled here)
        # --enable-linear-replayssm branch (confirmed by reading
        # hybrid_linear_attn_backend.py's _forward_metadata), so its value
        # never needs to change across replays.
        g_seq_lens_cpu_dummy = torch.zeros(1, dtype=torch.int64)

        cur_len = len(req.origin_input_ids) + len(req.output_ids)

        def _one_step(out_cache_loc_val, seq_len_after):
            g_seq_lens.fill_(seq_len_after)
            g_out_cache_loc.copy_(out_cache_loc_val)
            overrides = dict(
                reqs=[req],
                req_to_token_pool=runner.req_to_token_pool,
                token_to_kv_pool_allocator=runner.token_to_kv_pool_allocator,
                req_pool_indices=g_req_pool_indices,
                input_ids=g_input_ids,
                seq_lens=g_seq_lens,
                seq_lens_sum=int(seq_len_after),
                seq_lens_cpu=g_seq_lens_cpu_dummy,
                out_cache_loc=g_out_cache_loc,
                forward_mode=ForwardMode.DECODE,
                spec_info=None,
                sampling_info=None,
                capture_hidden_mode=None,
                return_hidden_states_before_norm=False,
                return_logprob=False,
                top_logprobs_nums=[0],
                token_ids_logprobs=[None],
            )
            draft_batch = dataclasses.replace(batch, **overrides)
            fb = ForwardBatch.init_new(draft_batch, runner)
            return runner.forward(fb)

        # Warmup on a side stream (standard idiom) -- long enough to trigger
        # any lazy one-time module-level setup so it does NOT happen for the
        # first time during capture (which would otherwise bake a one-off
        # setup kernel sequence into the graph, or outright fail capture).
        g_input_ids.fill_(0)
        warmup_stream = torch.cuda.Stream()
        warmup_stream.wait_stream(torch.cuda.current_stream())
        with torch.cuda.stream(warmup_stream):
            for i in range(5):
                ocl = runner.token_to_kv_pool_allocator.alloc(1)
                _one_step(ocl, cur_len + 1 + i)
        torch.cuda.current_stream().wait_stream(warmup_stream)

        g = torch.cuda.CUDAGraph()
        ocl = runner.token_to_kv_pool_allocator.alloc(1)
        with torch.cuda.graph(g, pool=_shared_graph_pool(self)):
            static_out = _one_step(ocl, cur_len + 6)

        self._draft_graph = g
        self._draft_graph_io = dict(
            input_ids=g_input_ids,
            req_pool_indices=g_req_pool_indices,
            seq_lens=g_seq_lens,
            out_cache_loc=g_out_cache_loc,
            out=static_out,
        )

    def _draft_decode_one_logits_graphed(self, draft_req_idx, token, seq_len_after):
        """Graphed replacement for _draft_decode_one_logits: same inputs
        (draft_req_idx = the REAL request's own pool slot, token = the id to
        feed, seq_len_after = the sequence length once this token is
        appended) and the same output shape, routed through the captured
        bs=1 DECODE CUDA graph instead of an eager per-step forward."""
        io = self._draft_graph_io
        out_cache_loc = self.draft_runner.token_to_kv_pool_allocator.alloc(1)
        io["input_ids"].fill_(token)
        io["seq_lens"].fill_(seq_len_after)
        io["req_pool_indices"].fill_(draft_req_idx)
        io["out_cache_loc"].copy_(out_cache_loc)
        self._draft_graph.replay()
        return io["out"].logits_output.next_token_logits[0]

    def _draft_extend(self, batch, req, tokens, prefix_len):
        """Extend the draft's own pool with `tokens` (prompt-mirror path).
        State-only update; the logits are unused (never sampled from here)."""
        fb = self._build_forward(
            batch,
            self.draft_runner,
            req,
            self._draft_slot[req.rid],
            tokens,
            prefix_len,
            extend=True,
        )
        self.draft_runner.forward(fb)

    def _build_forward(self, batch, runner, req, req_pool_idx, tokens, prefix_len, *, extend):
        """Construct a single-request ForwardBatch for `runner` (the draft's
        own ModelRunner) outside the scheduler's normal batch flow, by cloning
        `batch` (the real, currently-valid target-side ScheduleBatch passed
        into this round) and overriding only the fields that must differ.

        This sidesteps hand-enumerating ForwardBatch's ~60 mostly-optional
        fields: everything not explicitly overridden below comes from a batch
        the scheduler already built and validated (model_config, tree_cache,
        etc. are engine-lifetime/shared and correct as-is).
        """
        import dataclasses

        from sglang.srt.model_executor.forward_batch_info import (
            ForwardBatch,
            ForwardMode,
        )

        dev = runner.device
        n = len(tokens)
        input_ids = torch.tensor(tokens, dtype=torch.int64, device=dev)
        req_pool_indices = torch.tensor([req_pool_idx], dtype=torch.int64, device=dev)
        seq_len_after = prefix_len + n
        seq_lens = torch.tensor([seq_len_after], dtype=torch.int64, device=dev)
        out_cache_loc = runner.token_to_kv_pool_allocator.alloc(n)
        if out_cache_loc is None:
            raise RuntimeError("RWKV_SPEC: draft KV/state slot allocator exhausted")

        overrides = dict(
            reqs=[req],
            req_to_token_pool=runner.req_to_token_pool,
            token_to_kv_pool_allocator=runner.token_to_kv_pool_allocator,
            req_pool_indices=req_pool_indices,
            input_ids=input_ids,
            seq_lens=seq_lens,
            seq_lens_sum=int(seq_len_after),
            seq_lens_cpu=seq_lens.cpu(),
            out_cache_loc=out_cache_loc,
            forward_mode=ForwardMode.EXTEND if extend else ForwardMode.DECODE,
            spec_info=None,
            sampling_info=None,
            capture_hidden_mode=None,
            return_hidden_states_before_norm=False,
            return_logprob=False,
            top_logprobs_nums=[0],
            token_ids_logprobs=[None],
        )
        if extend:
            overrides.update(
                extend_lens=[n],
                prefix_lens=[prefix_len],
                extend_logprob_start_lens=[0],
                # MUST be overridden, not inherited. ForwardBatch.init_new feeds it to
                # compute_position as `extend_seq_lens_sum`, and compute_position_triton
                # allocates `torch.empty(that_sum)` while the kernel only fills what the
                # per-sequence lengths cover. Inheriting the target batch's value gives
                # the draft a positions tensor sized for the TARGET's token count with
                # an uninitialized tail, which the cuda-graph buffer registry then tries
                # to copy into a destination sliced to the draft's own length.
                # Invisible at bsz1 (the two counts coincide); with 8 concurrent
                # requests the target prefills ~105 tokens while this draft chunk is 6,
                # and the server dies on the first prefill.
                extend_num_tokens=n,
            )
        draft_batch = dataclasses.replace(batch, **overrides)
        return ForwardBatch.init_new(draft_batch, runner)


# --------------------------------------------------------------------------- #
# O(1) recurrent-state snapshot / restore (draft's own rollback). Used by both
# Strategy B (_commit_draft_rollback above) and the Strategy A reference below.
# --------------------------------------------------------------------------- #


def _snapshot(pool, layer_ids, slot):
    conv0, conv1, temporal = [], [], []
    for lid in layer_ids:
        cache = pool.mamba2_layer_cache(lid)
        conv0.append(cache.conv[0][slot].clone())
        conv1.append(cache.conv[1][slot].clone())
        temporal.append(cache.temporal[slot].clone())
    return (slot, torch.stack(conv0), torch.stack(conv1), torch.stack(temporal))


def _restore(pool, layer_ids, snap):
    slot, conv0, conv1, temporal = snap
    for i, lid in enumerate(layer_ids):
        cache = pool.mamba2_layer_cache(lid)
        cache.conv[0][slot].copy_(conv0[i])
        cache.conv[1][slot].copy_(conv1[i])
        cache.temporal[slot].copy_(temporal[i])


class _preserve:
    """Temporarily set a server_args attribute, restore on exit."""

    def __init__(self, obj, attr, value):
        self.obj, self.attr, self.value = obj, attr, value

    def __enter__(self):
        self.old = getattr(self.obj, self.attr)
        setattr(self.obj, self.attr, self.value)
        return self

    def __exit__(self, *exc):
        setattr(self.obj, self.attr, self.old)


# --------------------------------------------------------------------------- #
# STRATEGY A REFERENCE — UNUSED, kept only as a fallback per project decision
# (2026-07-07): if the rwkv7_backend.py is_target_verify addition that
# Strategy B depends on turns out to hit a wall, this is a complete alternate
# design that needs ZERO backend changes (it never sets ForwardMode.
# TARGET_VERIFY at all — it runs the target through an ordinary EXTEND forward
# and manually snapshots/restores around it, at the cost of a second forward
# pass to re-commit the accepted prefix whenever acceptance is partial).
#
# NOT wired into forward_batch_generation above and NOT maintained — its
# _draft_extend/_run_extend/_build_forward call signatures below predate the
# `batch` threading Strategy B needed and would need re-threading to run again.
# See project-spec-decode.md (memory) for the full Strategy A/B trade-off.
# --------------------------------------------------------------------------- #


def _stratA_decode_round(self, batch, on_publish):
    from sglang.srt.managers.scheduler import GenerationBatchResult

    flat_tokens: List[int] = []
    accept_lens: List[int] = []
    for i, req in enumerate(batch.reqs):
        appended = _stratA_round_one(self, batch, i, req)
        flat_tokens.extend(appended)
        accept_lens.append(len(appended) - 1)  # drafts accepted (excl. the bonus)
        if req.finished():
            self._release_draft_slot_by_rid(req.rid)

    _stratA_sync_batch_lens(self, batch)
    dev = batch.seq_lens.device
    next_token_ids = torch.tensor(flat_tokens, dtype=torch.int64, device=dev)
    accept_lens_t = torch.tensor(accept_lens, dtype=torch.int64, device=dev)
    new_seq_lens = batch.seq_lens  # already synced to include committed tokens
    if on_publish is not None:
        on_publish(new_seq_lens)
    return GenerationBatchResult(
        logits_output=None,
        next_token_ids=next_token_ids,
        accept_lens=accept_lens_t,
        num_correct_drafts_per_req_cpu=accept_lens,
        new_seq_lens=new_seq_lens,
        can_run_cuda_graph=False,
    )


def _stratA_round_one(self, batch, i, req) -> List[int]:
    target_req_idx = int(batch.req_pool_indices[i])
    draft_req_idx = self._draft_slot[req.rid]
    t_mslot = self._mamba_idx(self.target_pool, target_req_idx)
    d_mslot = self._mamba_idx(self.draft_pool, draft_req_idx)
    seq_committed = len(req.origin_input_ids) + len(req.output_ids)
    t_last = req.output_ids[-1] if req.output_ids else req.origin_input_ids[-1]

    snap_t = _snapshot(self.target_pool, self.target_layers, t_mslot)
    snap_d = _snapshot(self.draft_pool, self.draft_layers, d_mslot)

    # 1) draft proposes K tokens (K eager decode steps on its own pool).
    drafts = _stratA_draft_decode_k(self, req, draft_req_idx, t_last, seq_committed)

    # 2) chain-verify: ONE target extend over [t_last, d0..d_{K-2}] -> K logits.
    verify_in = [t_last] + drafts[:-1]
    target_argmax = _stratA_target_verify(
        self, req, target_req_idx, verify_in, seq_committed - 1
    )

    # 3) accept longest greedy-matching prefix.
    j = 0
    while j < self.k and int(target_argmax[j]) == drafts[j]:
        j += 1
    if j >= self.k:
        committed = list(drafts)  # both states already correct; keep
    else:
        bonus = int(target_argmax[j])
        committed = drafts[:j] + [bonus]
        _restore(self.target_pool, self.target_layers, snap_t)
        _restore(self.draft_pool, self.draft_layers, snap_d)
        commit_in = [t_last] + drafts[:j]  # J+1 tokens; bonus stays pending
        _stratA_target_verify(
            self, req, target_req_idx, commit_in, seq_committed - 1, capture=False
        )
        self._draft_extend(batch, req, commit_in, seq_committed - 1)

    appended: List[int] = []
    for tok in committed:
        req.output_ids.append(tok)
        appended.append(tok)
        req.check_finished()
        if req.finished():
            break
    req.spec_verify_ct = getattr(req, "spec_verify_ct", 0) + 1
    return appended


def _stratA_sync_batch_lens(self, batch):
    lens = [len(r.origin_input_ids) + len(r.output_ids) for r in batch.reqs]
    batch.seq_lens = torch.tensor(
        lens, dtype=batch.seq_lens.dtype, device=batch.seq_lens.device
    )
    if getattr(batch, "seq_lens_cpu", None) is not None:
        batch.seq_lens_cpu = torch.tensor(lens, dtype=torch.int64)
    batch.seq_lens_sum = int(sum(lens))


def _stratA_draft_decode_k(self, req, draft_req_idx, t_last, seq_committed) -> List[int]:
    """K eager greedy decode steps on the draft; returns K token ids."""
    vocab = self.draft_runner.model_config.vocab_size
    drafts: List[int] = []
    tok = t_last
    pos = seq_committed  # position of the token being fed (0-indexed length)
    for step in range(self.k):
        logits = self._draft_decode_one_logits(None, req, draft_req_idx, tok, pos)
        nxt = int(logits[:vocab].argmax(dim=-1))
        drafts.append(nxt)
        tok = nxt
        pos += 1
    return drafts


def _stratA_target_verify(self, req, target_req_idx, tokens, prefix_len, capture=True):
    fb = self._build_forward(
        None, self.target_runner, req, target_req_idx, tokens, prefix_len, extend=True
    )
    out = self.target_runner.forward(fb)
    if not capture:
        return None
    return _stratA_lm_head_argmax(self, out.logits_output.hidden_states)


def _stratA_lm_head_argmax(self, hidden):
    w = self.target_runner.model.lm_head.weight
    vocab = self.target_runner.model_config.vocab_size
    h = hidden.to(w.dtype)
    # per-row [1,H]@[H,V] on purpose: same reduction order as the M=1 decode
    # logits matmul, so near-tie argmaxes match the plain baseline (F0031).
    return torch.cat(
        [
            torch.matmul(h[i : i + 1], w.t()).float()[:, :vocab].argmax(dim=-1)
            for i in range(h.shape[0])
        ]
    )
